import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <nav className="flex items-center justify-between px-6 py-4 bg-white shadow-md">
  <div className="text-xl font-semibold text-gray-800">
    MyMedia
  </div>

  <div className="flex gap-6">
    <Link
      href="/"
      className="text-gray-600 hover:text-black transition font-medium"
    >
      Home
    </Link>

    <Link
      href="/queue"
      className="text-gray-600 hover:text-black transition font-medium"
    >
      All Media
    </Link>
  </div>
</nav>

        {children}
      </body>
    </html>
  );
}
